

frame_formatter_initial_reset_test 10
frame_formatter_soft_reset_test 10
frame_formatter_reset_scenarios_test 10
frame_formatter_ibypass_enable_test 10
frame_formatter_ibypass_disable_test 250
frame_formatter_sync_fifo_full_test 10
frame_formatter_async_fifo_empty_test 10
frame_formatter_vlan_tag_disable_test 250
frame_formatter_multiple_write_multiple_read_test 200
frame_formatter_multiple_write_one_read_test 250
frame_formatter_zero_write_multiple_read_test 10
frame_formatter_random_write_read_test 250
frame_formatter_ibypass_vlan_random_test 250 
